const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER'

const UPDATE_COMPRA_VALUE = 'UPDATE_COMPRA_VALUE'

const SET_MODAL = 'SET_MODAL'

const UPDATE_CARRINHO_VALUE = 'UPDATE_CARRINHO_VALUE'


export{
    SET_SELECTED_FILTER,UPDATE_CARRINHO_VALUE, UPDATE_COMPRA_VALUE,SET_MODAL
}